config/routes.rb
Valingo::Application.routes.draw do
  
  resources :pins

  devise_for :users

  get 'about' => 'pages#about'
  
  root :to => 'pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable, :recoverable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name 
  #:country_id (must figure out how to collect county data)
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	def home
  end

  	def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    @pin = Pin.new
    respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = Pin.new(params[:pin])
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update_attributes(params[:pin])
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
		<%= link_to "Valingo!", root_path %>
		by Kinan Alhoch
		</small>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->   
<div class="header">     
<nav class="navbar navbar-inverse custom navbar-fixed-top" role="navigation">

    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" 
                    data-toggle="collapse" 
                    data-target=".bs-example-navbar-collapse-1">                    
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
    
              <h1>  <%= link_to "Valingo!", root_path, class: "brand" %> </h1>
            
        </div>            

        <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="buttons">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
            <ul class="nav navbar-nav navbar-left">                        
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", about_path %></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">  
            
             <% if user_signed_in? %>   

                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            
            </ul>
            
            </div>                    
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	
	<head>
		 <title>Valingo</title>
		 <%= stylesheet_link_tag    "application", :media => "all" %>
		 <%= javascript_include_tag "application" %>
		 <%= csrf_meta_tags %>
	</head>
	
	<body>
		<%= render 'layouts/header' %>

		<div class="container-fluid">
		
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-#{name}") %>

		<% end %> 

	<%= yield %>

		<%= render 'layouts/footer' %>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About Valingo!</h1>

<p>
	<%= link_to "Valingo!","http:valingo.com" %> is a language exchange network designed to help people learn and practive new languages the way we all learned our original language... through conversation! Connect with people who speak the language you want to learn and talk to them - you'll learn from each other!
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>

	<h1> You're logged in!</h1>

<% else %>

	<div class="jumbotron">
	  <h1>Welcome to Valingo!</h1>
	  <p>
	  Learn a new language or practice one you already speak with real people live at <%= link_to "Valingo!","http:valingo.com" %>
	  the world's premier Language Exchange Network!
	  </p>
	  <p>
	    
	      <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	  
	  </p>
	</div>
	<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pins.each do |pin| %>
  <tr>
    <td><%= pin.description %></td>
    <td><%= link_to 'Show', pin %></td>
    <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
    <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @pin.description %>
</p>


<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>